baseURL = "https://karpova-lab.github.io/pyControl-D-Series-Breakout/"
languageCode = "en-us"
title = "D-series Breakout for pyControl"
publishDir = "../docs/"
theme = "book"


[params]
  BookSearch = false
  BookTheme = 'light'
  BookRepo =  'https://github.com/Karpova-Lab/pyControl-D-series-Breakout'
  

[markup.goldmark.renderer]
  unsafe = true

[markup]
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 4

  [markup.highlight] 
      style = 'friendly'